# Generated by Django 5.2.4 on 2025-10-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_admissionrecord_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionrecord',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
