# Generated by Django 5.2.4 on 2025-10-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_notice_featured_image_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=50, unique=True)),
                ('semester', models.PositiveIntegerField()),
                ('dob', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('day', 'Day')], default='day', max_length=10)),
            ],
        ),
    ]
