# Generated by Django 5.2.4 on 2025-10-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_admissionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionrecord',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionrecord',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admissionrecord',
            name='dob',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionrecord',
            name='shift',
            field=models.CharField(default='day', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shift',
            field=models.CharField(default='day', max_length=10),
        ),
    ]
