# Generated by Django 5.2.4 on 2025-10-27 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetoken',
            options={'ordering': ['-last_seen']},
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(help_text='The Firebase Cloud Messaging device token.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user this device belongs to. Can be null if not logged in yet.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user'], name='api_devicet_user_id_d47aee_idx'),
        ),
    ]
