# Generated by Django 5.2.4 on 2025-10-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_devicetoken_options_alter_devicetoken_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_time',
            new_name='start_time',
        ),
    ]
