# Generated by Django 5.2.4 on 2025-10-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_admissionrecord_email_admissionrecord_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='Default Name', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='unknown@example.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admissionrecord',
            name='dob',
            field=models.CharField(help_text='Format: YYYY/MM/DD (BS)', max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionrecord',
            name='shift',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.CharField(help_text='Format: YYYY/MM/DD (BS)', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shift',
            field=models.CharField(help_text="Type either 'morning' or 'day' manually", max_length=10),
        ),
    ]
