# Generated by Django 5.2.4 on 2025-10-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_event_time_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='semester',
            field=models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester'), ('7', '7th Semester'), ('8', '8th Semester')], default=7, max_length=2),
            preserve_default=False,
        ),
    ]
