# Generated by Django 5.2.4 on 2025-10-09 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_email_profile_name_alter_admissionrecord_dob_and_more'),
    ]

    operations = [
    ]
