# Generated by Django 5.2.4 on 2025-10-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20251009_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionrecord',
            name='address',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
    ]
