# Generated by Django 5.2.4 on 2025-10-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_admissionrecord_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
